#!/usr/bin/env python3
"""Compare one SemanticKITTI Drive-OccWorld-light info with one nuScenes info.

用途：
    第一阶段实现 SemanticKITTI 数据集时，需要知道新 converter 生成的 pkl
    与 Drive-OccWorld 当前 nuScenes pkl 在字段组织上有哪些差异。

本脚本会分别读取：
    1. tools/semantickitti_converter.py 生成的 SemanticKITTI pkl；
    2. nuScenes ``nuscenes_infos_temporal_train_new_v2.pkl``；

然后各取一个样本，打印：
    - 顶层 pkl 结构；
    - info 字段列表；
    - 共有字段 / 各自独有字段；
    - 关键字段的类型、shape、简短值；
    - cams / pose / occupancy / planning 相关字段摘要。

注意：
    这个脚本只做只读分析，不修改任何 pkl。
"""

import argparse
import os.path as osp
import pickle
from collections.abc import Mapping

import numpy as np


DEFAULT_NEW_TRAIN_ANN_FILE = (
    '/c20250502/wangyushen/Weights/drive-occworld/'
    'nuscenes_infos_temporal_train_new_v2.pkl'
)


def parse_args():
    parser = argparse.ArgumentParser(
        description='Compare SemanticKITTI light PKL and nuScenes v2 PKL.')
    parser.add_argument('--semkitti-pkl', required=True,
                        help='PKL generated by tools/semantickitti_converter.py')
    parser.add_argument('--nuscenes-pkl', default=DEFAULT_NEW_TRAIN_ANN_FILE,
                        help='nuScenes v2 PKL path')
    parser.add_argument('--semkitti-index', type=int, default=0,
                        help='sample index in SemanticKITTI infos')
    parser.add_argument('--nuscenes-index', type=int, default=0,
                        help='sample index in nuScenes infos')
    parser.add_argument('--max-keys', type=int, default=120,
                        help='max number of keys to print in long key lists')
    return parser.parse_args()


def load_pkl(path):
    if not osp.isfile(path):
        raise FileNotFoundError(f'Missing pkl: {path}')
    with open(path, 'rb') as f:
        return pickle.load(f)


def get_infos(data):
    """Return infos list from common pkl structures.

    Supports:
      - {'infos': [info, ...], 'metadata': ...}
      - {'infos': {'scene_name': [info, ...]}, 'metadata': ...}
      - [info, ...]
    """
    if isinstance(data, list):
        return data
    if not isinstance(data, Mapping):
        raise TypeError(f'Unsupported pkl root type: {type(data)}')
    infos = data.get('infos', None)
    if isinstance(infos, list):
        return infos
    if isinstance(infos, Mapping):
        flat_infos = []
        for scene_name in sorted(infos.keys()):
            flat_infos.extend(infos[scene_name])
        return flat_infos
    raise TypeError(f'Unsupported infos type: {type(infos)}')


def shape_dtype_value(value, max_str=120):
    """Compactly describe one field value."""
    if isinstance(value, np.ndarray):
        return f'ndarray shape={value.shape}, dtype={value.dtype}'
    if hasattr(value, 'shape') and hasattr(value, 'dtype'):
        return f'{type(value).__name__} shape={tuple(value.shape)}, dtype={value.dtype}'
    if isinstance(value, (list, tuple)):
        if value and isinstance(value[0], (int, float, str, bool, np.number)):
            text = repr(value[:8])
            if len(value) > 8:
                text = text[:-1] + ', ...]'
            return f'{type(value).__name__} len={len(value)}, value={text}'
        return f'{type(value).__name__} len={len(value)}'
    if isinstance(value, Mapping):
        keys = list(value.keys())
        return f'dict len={len(keys)}, keys={keys[:8]}'
    text = repr(value)
    if len(text) > max_str:
        text = text[:max_str] + '...'
    return f'{type(value).__name__}: {text}'


def print_root_summary(name, data):
    print(f'\n{"=" * 100}')
    print(f'{name} PKL root summary')
    print(f'{"=" * 100}')
    print(f'root type: {type(data)}')
    if isinstance(data, Mapping):
        print(f'root keys: {list(data.keys())}')
        metadata = data.get('metadata', None)
        if metadata is not None:
            print(f'metadata: {shape_dtype_value(metadata)}')
            if isinstance(metadata, Mapping):
                for key, value in metadata.items():
                    print(f'  metadata[{key!r}]: {shape_dtype_value(value)}')


def print_key_list(title, keys, max_keys):
    keys = sorted(keys)
    print(f'\n{title} ({len(keys)} keys)')
    if len(keys) <= max_keys:
        print(keys)
    else:
        print(keys[:max_keys])
        print(f'... omitted {len(keys) - max_keys} keys')


def print_key_comparison(sem_info, nusc_info, max_keys):
    sem_keys = set(sem_info.keys())
    nusc_keys = set(nusc_info.keys())
    print_key_list('Common keys', sem_keys & nusc_keys, max_keys)
    print_key_list('SemanticKITTI-only keys', sem_keys - nusc_keys, max_keys)
    print_key_list('nuScenes-only keys', nusc_keys - sem_keys, max_keys)


def print_selected_fields(name, info):
    print(f'\n{"-" * 100}')
    print(f'{name} selected field summary')
    print(f'{"-" * 100}')
    selected_keys = [
        'token', 'sample_idx', 'scene_token', 'scene_name', 'location',
        'frame_idx', 'pose_idx', 'timestamp', 'prev', 'next',
        'img_filename', 'lidar_path', 'occ_path', 'voxel_path',
        'lidar2img', 'cams',
        'lidar2ego_translation', 'lidar2ego_rotation',
        'ego2global_translation', 'ego2global_rotation', 'can_bus',
        'sdc_planning', 'sdc_planning_mask', 'command',
        'sample_traj_state', 'sample_annotations',
        'gt_ego_his_trajs', 'gt_ego_fut_trajs', 'gt_ego_fut_masks',
        'gt_ego_fut_cmd', 'fut_valid_flag',
        'gt_boxes', 'gt_names', 'ann_infos',
    ]
    for key in selected_keys:
        if key in info:
            print(f'{key}: {shape_dtype_value(info[key])}')
        else:
            print(f'{key}: <MISSING>')


def print_cams_summary(name, info):
    print(f'\n{"-" * 100}')
    print(f'{name} cams summary')
    print(f'{"-" * 100}')
    cams = info.get('cams', None)
    if not isinstance(cams, Mapping):
        print(f'cams is not a dict: {shape_dtype_value(cams)}')
        return
    print(f'num cameras: {len(cams)}')
    for cam_name, cam_info in cams.items():
        print(f'\n[{cam_name}]')
        if not isinstance(cam_info, Mapping):
            print(shape_dtype_value(cam_info))
            continue
        for key in [
                'data_path', 'type', 'cam_intrinsic', 'lidar2img',
                'sensor2lidar_rotation', 'sensor2lidar_translation',
                'sensor2ego_rotation', 'sensor2ego_translation']:
            if key in cam_info:
                value = cam_info[key]
                if key in ('cam_intrinsic', 'lidar2img'):
                    arr = np.asarray(value)
                    print(f'  {key}: shape={arr.shape}, dtype={arr.dtype}')
                else:
                    print(f'  {key}: {shape_dtype_value(value)}')
        extra = sorted(set(cam_info.keys()) - {
            'data_path', 'type', 'cam_intrinsic', 'lidar2img',
            'sensor2lidar_rotation', 'sensor2lidar_translation',
            'sensor2ego_rotation', 'sensor2ego_translation'})
        if extra:
            print(f'  extra keys: {extra}')


def print_all_field_shapes(name, info, max_keys):
    print(f'\n{"-" * 100}')
    print(f'{name} all field compact summary')
    print(f'{"-" * 100}')
    keys = sorted(info.keys())
    for key in keys[:max_keys]:
        print(f'{key}: {shape_dtype_value(info[key])}')
    if len(keys) > max_keys:
        print(f'... omitted {len(keys) - max_keys} fields')


def main():
    args = parse_args()

    sem_data = load_pkl(args.semkitti_pkl)
    nusc_data = load_pkl(args.nuscenes_pkl)

    print_root_summary('SemanticKITTI', sem_data)
    print_root_summary('nuScenes', nusc_data)

    sem_infos = get_infos(sem_data)
    nusc_infos = get_infos(nusc_data)
    print(f'\nSemanticKITTI infos length: {len(sem_infos)}')
    print(f'nuScenes infos length: {len(nusc_infos)}')

    if not (0 <= args.semkitti_index < len(sem_infos)):
        raise IndexError(
            f'semkitti-index={args.semkitti_index} out of range [0, {len(sem_infos)-1}]')
    if not (0 <= args.nuscenes_index < len(nusc_infos)):
        raise IndexError(
            f'nuscenes-index={args.nuscenes_index} out of range [0, {len(nusc_infos)-1}]')

    sem_info = sem_infos[args.semkitti_index]
    nusc_info = nusc_infos[args.nuscenes_index]

    print_key_comparison(sem_info, nusc_info, args.max_keys)
    print_selected_fields('SemanticKITTI', sem_info)
    print_selected_fields('nuScenes', nusc_info)
    print_cams_summary('SemanticKITTI', sem_info)
    print_cams_summary('nuScenes', nusc_info)
    print_all_field_shapes('SemanticKITTI', sem_info, args.max_keys)
    print_all_field_shapes('nuScenes', nusc_info, args.max_keys)


if __name__ == '__main__':
    main()
