#!/usr/bin/env python3
"""Compare one SemanticKITTI Drive-OccWorld-light info with one nuScenes info.

用途：
    第一阶段实现 SemanticKITTI 数据集时，需要知道新 converter 生成的 pkl
    与 Drive-OccWorld 当前 nuScenes pkl 在字段组织上有哪些差异。

本脚本会分别读取：
    1. tools/semantickitti_converter.py 生成的 SemanticKITTI pkl；
    2. nuScenes ``nuscenes_infos_temporal_train_new_v2.pkl``；

然后各取一个样本，打印：
    - 顶层 pkl 结构；
    - info 字段列表；
    - 共有字段 / 各自独有字段；
    - 关键字段的类型、shape、简短值；
    - cams / pose / occupancy / planning 相关字段摘要。

注意：
    这个脚本只做只读分析，不修改任何 pkl。
"""

import argparse
import os.path as osp
import pickle
from collections.abc import Mapping

import numpy as np


DEFAULT_NEW_TRAIN_ANN_FILE = (
    '/c20250502/wangyushen/Weights/drive-occworld/'
    'nuscenes_infos_temporal_train_new_v2.pkl'
)

DEFAULT_NUSCENES_OCC_ROOT = (
    '/c20250502/wangyushen/Datasets/nuScenes-Occupancy-v0.1'
)


def parse_args():
    parser = argparse.ArgumentParser(
        description='Compare SemanticKITTI light PKL and nuScenes v2 PKL.')
    parser.add_argument('--semkitti-pkl', required=True,
                        help='PKL generated by tools/semantickitti_converter.py')
    parser.add_argument('--nuscenes-pkl', default=DEFAULT_NEW_TRAIN_ANN_FILE,
                        help='nuScenes v2 PKL path')
    parser.add_argument('--nuscenes-occ-root', default=DEFAULT_NUSCENES_OCC_ROOT,
                        help=('nuScenes occupancy root used by LoadOccupancy. '
                              'Expected path pattern: '
                              '<root>/scene_{scene_token}/occupancy/{lidar_token}.npy'))
    parser.add_argument('--semkitti-index', type=int, default=0,
                        help='sample index in SemanticKITTI infos')
    parser.add_argument('--nuscenes-index', type=int, default=0,
                        help='sample index in nuScenes infos')
    parser.add_argument('--max-keys', type=int, default=120,
                        help='max number of keys to print in long key lists')
    return parser.parse_args()


def load_pkl(path):
    if not osp.isfile(path):
        raise FileNotFoundError(f'Missing pkl: {path}')
    with open(path, 'rb') as f:
        return pickle.load(f)


def get_infos(data):
    """Return infos list from common pkl structures.

    Supports:
      - {'infos': [info, ...], 'metadata': ...}
      - {'infos': {'scene_name': [info, ...]}, 'metadata': ...}
      - [info, ...]
    """
    if isinstance(data, list):
        return data
    if not isinstance(data, Mapping):
        raise TypeError(f'Unsupported pkl root type: {type(data)}')
    infos = data.get('infos', None)
    if isinstance(infos, list):
        return infos
    if isinstance(infos, Mapping):
        flat_infos = []
        for scene_name in sorted(infos.keys()):
            flat_infos.extend(infos[scene_name])
        return flat_infos
    raise TypeError(f'Unsupported infos type: {type(infos)}')


def shape_dtype_value(value, max_str=120):
    """Compactly describe one field value."""
    if isinstance(value, np.ndarray):
        return f'ndarray shape={value.shape}, dtype={value.dtype}'
    if hasattr(value, 'shape') and hasattr(value, 'dtype'):
        return f'{type(value).__name__} shape={tuple(value.shape)}, dtype={value.dtype}'
    if isinstance(value, (list, tuple)):
        if value and isinstance(value[0], (int, float, str, bool, np.number)):
            text = repr(value[:8])
            if len(value) > 8:
                text = text[:-1] + ', ...]'
            return f'{type(value).__name__} len={len(value)}, value={text}'
        return f'{type(value).__name__} len={len(value)}'
    if isinstance(value, Mapping):
        keys = list(value.keys())
        return f'dict len={len(keys)}, keys={keys[:8]}'
    text = repr(value)
    if len(text) > max_str:
        text = text[:max_str] + '...'
    return f'{type(value).__name__}: {text}'


def print_root_summary(name, data):
    print(f'\n{"=" * 100}')
    print(f'{name} PKL root summary')
    print(f'{"=" * 100}')
    print(f'root type: {type(data)}')
    if isinstance(data, Mapping):
        print(f'root keys: {list(data.keys())}')
        metadata = data.get('metadata', None)
        if metadata is not None:
            print(f'metadata: {shape_dtype_value(metadata)}')
            if isinstance(metadata, Mapping):
                for key, value in metadata.items():
                    print(f'  metadata[{key!r}]: {shape_dtype_value(value)}')


def print_key_list(title, keys, max_keys):
    keys = sorted(keys)
    print(f'\n{title} ({len(keys)} keys)')
    if len(keys) <= max_keys:
        print(keys)
    else:
        print(keys[:max_keys])
        print(f'... omitted {len(keys) - max_keys} keys')


def print_key_comparison(sem_info, nusc_info, max_keys):
    sem_keys = set(sem_info.keys())
    nusc_keys = set(nusc_info.keys())
    print_key_list('Common keys', sem_keys & nusc_keys, max_keys)
    print_key_list('SemanticKITTI-only keys', sem_keys - nusc_keys, max_keys)
    print_key_list('nuScenes-only keys', nusc_keys - sem_keys, max_keys)


def print_selected_fields(name, info):
    print(f'\n{"-" * 100}')
    print(f'{name} selected field summary')
    print(f'{"-" * 100}')
    selected_keys = [
        'token', 'sample_idx', 'scene_token', 'scene_name', 'location',
        'frame_idx', 'pose_idx', 'timestamp', 'prev', 'next',
        'img_filename', 'lidar_path', 'occ_path', 'voxel_path',
        'lidar2img', 'cams',
        'lidar2ego_translation', 'lidar2ego_rotation',
        'ego2global_translation', 'ego2global_rotation', 'can_bus',
        'sdc_planning', 'sdc_planning_mask', 'command',
        'sample_traj_state', 'sample_annotations',
        'gt_ego_his_trajs', 'gt_ego_fut_trajs', 'gt_ego_fut_masks',
        'gt_ego_fut_cmd', 'fut_valid_flag',
        'gt_boxes', 'gt_names', 'ann_infos',
    ]
    for key in selected_keys:
        if key in info:
            print(f'{key}: {shape_dtype_value(info[key])}')
        else:
            print(f'{key}: <MISSING>')


def print_cams_summary(name, info):
    print(f'\n{"-" * 100}')
    print(f'{name} cams summary')
    print(f'{"-" * 100}')
    cams = info.get('cams', None)
    if not isinstance(cams, Mapping):
        print(f'cams is not a dict: {shape_dtype_value(cams)}')
        return
    print(f'num cameras: {len(cams)}')
    for cam_name, cam_info in cams.items():
        print(f'\n[{cam_name}]')
        if not isinstance(cam_info, Mapping):
            print(shape_dtype_value(cam_info))
            continue
        for key in [
                'data_path', 'type', 'cam_intrinsic', 'lidar2img',
                'sensor2lidar_rotation', 'sensor2lidar_translation',
                'sensor2ego_rotation', 'sensor2ego_translation']:
            if key in cam_info:
                value = cam_info[key]
                if key in ('cam_intrinsic', 'lidar2img'):
                    arr = np.asarray(value)
                    print(f'  {key}: shape={arr.shape}, dtype={arr.dtype}')
                else:
                    print(f'  {key}: {shape_dtype_value(value)}')
        extra = sorted(set(cam_info.keys()) - {
            'data_path', 'type', 'cam_intrinsic', 'lidar2img',
            'sensor2lidar_rotation', 'sensor2lidar_translation',
            'sensor2ego_rotation', 'sensor2ego_translation'})
        if extra:
            print(f'  extra keys: {extra}')


def print_all_field_shapes(name, info, max_keys):
    print(f'\n{"-" * 100}')
    print(f'{name} all field compact summary')
    print(f'{"-" * 100}')
    keys = sorted(info.keys())
    for key in keys[:max_keys]:
        print(f'{key}: {shape_dtype_value(info[key])}')
    if len(keys) > max_keys:
        print(f'... omitted {len(keys) - max_keys} fields')


def build_token_index(infos):
    """Build token -> info mapping for checking prev/current/next links."""
    token_to_info = {}
    for info in infos:
        token = info.get('token', None)
        if token:
            token_to_info[token] = info
    return token_to_info


def get_occupancy_fields(info):
    """Return explicit dense occupancy path fields stored in one info.

    当前 SemanticKITTI-light pkl 逐帧显式保存：
      - occ_path: dense occupancy .npy 标签路径

    Drive-OccWorld nuScenes pkl 通常不逐帧保存 occ_path，而是保存：
      - scene_token
      - lidar_token

    nuScenes 的真实 dense occupancy 文件路径应由
    build_nuscenes_occ_path() / print_nuscenes_temporal_occ_file_check()
    按 LoadOccupancy 规则拼接：
      <occ_root>/scene_{scene_token}/occupancy/{lidar_token}.npy

    因此这里不再把 lidarseg 或 sample_annotations 当作 occupancy 标注字段：
      - lidarseg 是 nuScenes LiDAR segmentation 相关字段；
      - sample_annotations 是 3D box annotation；
    它们都不能等价于 Drive-OccWorld 训练用的 dense occupancy .npy。
    """
    candidate_keys = [
        'occ_path',
        'voxel_path',
    ]
    return {key: info[key] for key in candidate_keys if key in info}


def field_points_to_existing_file(value):
    """Best-effort check whether an occupancy-related field points to a file."""
    if isinstance(value, str):
        return osp.isfile(value)
    if isinstance(value, (list, tuple)) and value and isinstance(value[0], str):
        return any(osp.isfile(item) for item in value)
    return None


def print_temporal_occupancy_check(name, infos, info):
    """Check whether prev/current/next tokens have explicit occupancy path fields.

    这里检查的是 pkl 级别的可用性：
      1. prev/token/next 能否在当前 pkl 的 infos 中找到对应 info；
      2. 对应 info 是否显式保存 occ_path / voxel_path；
      3. 若字段值是路径，则顺手检查文件是否存在。

    注意：
      - SemanticKITTI-light 当前会保存 occ_path，因此这里能直接判断；
      - nuScenes Drive-OccWorld 通常不保存 occ_path，所以这里显示缺失是正常的；
      - nuScenes 是否真的有 dense occupancy 标注，请看后面的
        print_nuscenes_temporal_occ_file_check() 输出。
    """
    print(f'\n{"-" * 100}')
    print(f'{name} prev/current/next explicit occupancy path field check')
    print(f'{"-" * 100}')

    token_to_info = build_token_index(infos)
    rows = [
        ('prev', info.get('prev', '')),
        ('current', info.get('token', '')),
        ('next', info.get('next', '')),
    ]

    for role, token in rows:
        if not token:
            print(f'{role}: token=<EMPTY>, info_found=False, occ_fields=<N/A>')
            continue

        linked_info = token_to_info.get(token, None)
        if linked_info is None:
            print(f'{role}: token={token}, info_found=False, occ_fields=<N/A>')
            continue

        occ_fields = get_occupancy_fields(linked_info)
        if not occ_fields:
            print(f'{role}: token={token}, info_found=True, occ_fields=<MISSING>')
            continue

        print(f'{role}: token={token}, info_found=True')
        for key, value in occ_fields.items():
            exists = field_points_to_existing_file(value)
            exists_text = ''
            if exists is not None:
                exists_text = f', file_exists={exists}'
            print(f'  {key}: {shape_dtype_value(value)}{exists_text}')


def build_nuscenes_occ_path(nuscenes_occ_root, info):
    """Build Drive-OccWorld nuScenes occupancy path from one frame info.

    LoadOccupancy 中的读取规则是：
        rel_path = 'scene_{scene_token}/occupancy/{lidar_token}.npy'
        np.load(os.path.join(occ_root, rel_path))

    因此 nuScenes pkl 不需要逐帧保存 occ_path，只要保存 scene_token
    和 lidar_token，就能在给定 occ_root 后确定 occupancy 标注路径。
    """
    scene_token = info.get('scene_token', None)
    lidar_token = info.get('lidar_token', None)
    if scene_token is None or lidar_token is None:
        return None
    rel_path = f'scene_{scene_token}/occupancy/{lidar_token}.npy'
    return osp.join(nuscenes_occ_root, rel_path)


def print_nuscenes_temporal_occ_file_check(infos, info, nuscenes_occ_root):
    """Check whether nuScenes prev/current/next have real occupancy files.

    这个检查用于判断 nuScenes pkl 中的 prev/next 是否落在有 occupancy 标注的
    sample 上。若 prev/next 能在 pkl 中找到，并且按 LoadOccupancy 规则拼出的
    .npy 文件存在，则说明该相邻 token 是可用于 occupancy 监督/对齐的帧。
    """
    print(f'\n{"-" * 100}')
    print('nuScenes prev/current/next real occupancy file check')
    print(f'{"-" * 100}')
    print(f'nuscenes_occ_root: {nuscenes_occ_root}')
    print('path rule: <root>/scene_{scene_token}/occupancy/{lidar_token}.npy')

    token_to_info = build_token_index(infos)
    rows = [
        ('prev', info.get('prev', '')),
        ('current', info.get('token', '')),
        ('next', info.get('next', '')),
    ]

    for role, token in rows:
        if not token:
            print(f'{role}: token=<EMPTY>, info_found=False, occ_path=<N/A>')
            continue

        linked_info = token_to_info.get(token, None)
        if linked_info is None:
            print(f'{role}: token={token}, info_found=False, occ_path=<N/A>')
            continue

        occ_path = build_nuscenes_occ_path(nuscenes_occ_root, linked_info)
        if occ_path is None:
            print(
                f'{role}: token={token}, info_found=True, '
                f'scene_token/lidar_token=<MISSING>, occ_path=<N/A>')
            continue

        print(
            f'{role}: token={token}, info_found=True, '
            f"scene_token={linked_info.get('scene_token')}, "
            f"lidar_token={linked_info.get('lidar_token')}, "
            f'occ_file_exists={osp.isfile(occ_path)}')
        print(f'  occ_path: {occ_path}')


def main():
    args = parse_args()

    sem_data = load_pkl(args.semkitti_pkl)
    nusc_data = load_pkl(args.nuscenes_pkl)

    print_root_summary('SemanticKITTI', sem_data)
    print_root_summary('nuScenes', nusc_data)

    sem_infos = get_infos(sem_data)
    nusc_infos = get_infos(nusc_data)
    print(f'\nSemanticKITTI infos length: {len(sem_infos)}')
    print(f'nuScenes infos length: {len(nusc_infos)}')

    if not (0 <= args.semkitti_index < len(sem_infos)):
        raise IndexError(
            f'semkitti-index={args.semkitti_index} out of range [0, {len(sem_infos)-1}]')
    if not (0 <= args.nuscenes_index < len(nusc_infos)):
        raise IndexError(
            f'nuscenes-index={args.nuscenes_index} out of range [0, {len(nusc_infos)-1}]')

    sem_info = sem_infos[args.semkitti_index]
    nusc_info = nusc_infos[args.nuscenes_index]

    print_key_comparison(sem_info, nusc_info, args.max_keys)
    print_selected_fields('SemanticKITTI', sem_info)
    print_selected_fields('nuScenes', nusc_info)
    print_temporal_occupancy_check('SemanticKITTI', sem_infos, sem_info)
    print_temporal_occupancy_check('nuScenes', nusc_infos, nusc_info)
    print_nuscenes_temporal_occ_file_check(
        nusc_infos, nusc_info, args.nuscenes_occ_root)
    print_cams_summary('SemanticKITTI', sem_info)
    print_cams_summary('nuScenes', nusc_info)
    print_all_field_shapes('SemanticKITTI', sem_info, args.max_keys)
    print_all_field_shapes('nuScenes', nusc_info, args.max_keys)


if __name__ == '__main__':
    main()
